# This file is auto-generated by `.github/workflows/update-manifests.yml`
# List of tags and Git revs at https://github.com/argumentcomputer/lean4-nix-manifests
# Revs are needed to use `builtins.fetchGit` in pure evaluation mode
{
  "v4.11.0" = "b91b040c5f420cd4de0d98d2f59f483f269fe119";
  "v4.12.0" = "08eaca538b28feb354e4e4d2f24e784d44a7440f";
  "v4.13.0" = "03845d8b92ab5da376b0296e388d62ad20b796a6";
  "v4.14.0" = "c5f2bdf1928ee015bf97b48550edfc3c9b09e61c";
  "v4.15.0" = "73e565fee6650d7db714028a3d8f1791744c662f";
  "v4.16.0" = "947e55ce2c6ae157c92ca3bc690fc684a18e26b7";
  "v4.17.0" = "d595484bab95855efde287c5450207160385810b";
  "v4.18.0" = "9c9ed4a97041037677e321d608701d5c1d8acaf9";
  "v4.19.0" = "c05b8cf10f535418fdd4405f709c8725728f4458";
  "v4.20.0" = "9200850f8effcc47da518fb78d2d1039d55d4138";
  "v4.20.1" = "c4f8ca4e7af867ebd0ec3439aaa4a2ae5d6ab089";
}
