{
  lib,
  fetchurl,
  stdenv,
  zstd,
  cadical,
  clang,
  lld,
  makeWrapper,
  fixDarwinDylibNames,
  autoPatchelfHook,
  ...
}:
let
  inherit (stdenv.hostPlatform) system;

  # Pinned release hashes, generated by `nix run .#toolchain-fetch`. Nix cannot
  # fetch a tarball whose hash is unknown at evaluation time, so these must be
  # vendored rather than looked up at build time.
  data = builtins.fromJSON (builtins.readFile ../data/toolchains.json);

  # Fetches a released Lean toolchain and patches it to run under Nix: the
  # shipped clang and its headers are replaced with the nixpkgs ones, ELF
  # interpreters are rewritten on Linux, dylib names fixed on Darwin, and the
  # entry points get `lld` on `PATH` so `leanc` can link, plus `cadical`, which
  # `bv-decide` shells out to and the release tarball does not ship.
  fetchBinaryLean =
    tag: toolchain:
    let
      version = builtins.substring 1 (-1) tag;
      system-tag = builtins.getAttr system {
        x86_64-linux = "linux";
        aarch64-linux = "linux_aarch64";
        x86_64-darwin = "darwin";
        aarch64-darwin = "darwin_aarch64";
      };
      tarball = fetchurl {
        url =
          toolchain.${system}.url
            or "https://github.com/leanprover/lean4/releases/download/${tag}/lean-${version}-${system-tag}.tar.zst";
        hash = toolchain.${system}.hash;
      };
      compile-bin = lib.makeBinPath [
        lld
        cadical
      ];
    in
    stdenv.mkDerivation {
      pname = "lean";
      inherit version;
      src = tarball;
      nativeBuildInputs = [
        zstd
        makeWrapper
      ]
      ++ lib.optional stdenv.isDarwin fixDarwinDylibNames
      ++ lib.optionals stdenv.isLinux [
        autoPatchelfHook
        stdenv.cc.cc.lib
      ];
      # Use `rm -f` here since not all of these executables exist on every platform
      installPhase = ''
        mkdir -p $out/
        rm -f bin/{clang,ld.lld,llvm-ar}
        ln -s ${clang}/bin/clang bin/

        # Replace includes
        rm -r include/clang
        ln -s ${clang}/resource-root/include include/clang

        # Remove shipped clang libraries
        rm -r lib/clang

        mv ./* $out/

        wrapProgram $out/bin/lean \
          --prefix PATH : ${compile-bin}
        wrapProgram $out/bin/leanmake \
          --prefix PATH : ${compile-bin}
        wrapProgram $out/bin/leanc \
          --prefix PATH : ${compile-bin}
        wrapProgram $out/bin/lake \
          --prefix PATH : ${compile-bin}
      '';
      meta.mainProgram = "lean";
    };

  parseTag =
    toolchain:
    builtins.addErrorContext "Only leanprover/lean4:{tag} toolchains for stable versions are supported." (
      builtins.head (
        builtins.match "^[[:space:]]*leanprover/lean4:([a-zA-Z0-9\\-\\.]+)[[:space:]]*$" toolchain
      )
    );
in
rec {
  # Every version in `data/toolchains.json`, as derivations keyed by tag.
  toolchains = builtins.mapAttrs fetchBinaryLean data;

  # `leanprover/lean4:v4.33.0` -> derivation
  fromToolchain =
    toolchain:
    let
      tag = parseTag toolchain;
    in
    toolchains.${tag}
      or (throw "Lean ${tag} is not listed in data/toolchains.json. Available: ${builtins.concatStringsSep ", " (builtins.attrNames toolchains)}");

  # Path to a `lean-toolchain` file -> derivation
  fromToolchainFile = file: fromToolchain (builtins.readFile file);
}
