# Build and upload Lean binaries to Cachix cache
name: Nix CI

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test LSpec template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: argumentcomputer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Patch flake.nix with current commit in template
        run: |
          sed -i 's|github:argumentcomputer/lean4-nix|path:../../|g' flake.nix
        working-directory : ${{ github.workspace }}/templates/lspec-project
      - run: nix build .#default .#lspec
        working-directory : ${{ github.workspace }}/templates/lspec-project
      - run: nix run .#lspec
        working-directory : ${{ github.workspace }}/templates/lspec-project

  cache:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Build and cache Lean artifacts
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: argumentcomputer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix build .#cacheRoots

