# Build and upload Lean binaries to Cachix cache
name: Nix CI

on:
  push:
    branches: dev
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests and cache lean4-nix
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: argumentcomputer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#cacheRoots
      - run: nix run
        working-directory: ${{ github.workspace }}/templates/minimal
      - run: nix run
        working-directory: ${{ github.workspace }}/templates/dependency
      - run: nix run
        working-directory: ${{ github.workspace }}/templates/ffi-rust

