# Build and upload Lean binaries to Cachix cache
name: Nix CI

on:
  push:
    branches: ["dev", "v4.16.0"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and cache Lean
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: argumentcomputer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#cacheRoots
      - run: nix build
        working-directory: ${{ github.workspace }}/templates/minimal

