# Build, test, and upload Lean binaries to Cachix cache for x86_64-linux and aarch64-darwin
name: Nix CI

on:
  push:
    branches: dev
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and cache lean4-nix
    strategy:
      matrix:
        os: [warp-ubuntu-latest-x64-16x, warp-macos-latest-arm64-6x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: argumentcomputer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#cacheRoots

  test:
    name: Test templates
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, warp-macos-latest-arm64-6x]
        template: [minimal, dependency, ffi-rust]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: argumentcomputer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: |
          sed -i '/lean4-nix = {/,/};/s|url = "github:[^"]*"|url = "path:../.."|' flake.nix
          nix run
        working-directory: ${{ github.workspace }}/templates/${{ matrix.template }}
